// Auto-generated by scripts/generate-index.mjs - do not edit manually.

import de from './locales/de.json' with { type: 'json' };
import en from './locales/en.json' with { type: 'json' };
import es from './locales/es.json' with { type: 'json' };
import ja from './locales/ja.json' with { type: 'json' };
import ru from './locales/ru.json' with { type: 'json' };

export { de, en, es, ja, ru };

export default {
  de,
  en,
  es,
  ja,
  ru,
};
