import { readdirSync, writeFileSync } from "node:fs"
import { join, basename } from "node:path"
import { fileURLToPath } from "node:url"

const root = fileURLToPath(new URL("..", import.meta.url))
const localesDir = join(root, "locales")
const outFile = join(root, "index.js")

const files = readdirSync(localesDir)
  .filter(f => f.endsWith(".json"))
  .sort()

if (files.length === 0) {
  console.error("No locale files found in locales/")
  process.exit(1)
}

const codes = files.map(f => basename(f, ".json"))

const imports = codes.map(code => `import ${code} from './locales/${code}.json' with { type: 'json' };`)
const namedExports = `export { ${codes.join(", ")} };`
const defaultExport = `export default {\n${codes.map(code => `  ${code},\n`).join("")}};`

const content = `// Auto-generated by scripts/generate-index.mjs - do not edit manually.\n\n${imports.join("\n")}\n\n${namedExports}\n\n${defaultExport}\n`

writeFileSync(outFile, content)
console.log(`Generated index.js for ${codes.length} locales: ${codes.join(", ")}`)